[package]
name = "mp3-metadata"
version = "0.2.3"
authors = ["Guillaume Gomez <guillaume1.gomez@gmail.com>"]

description = "Metadata parser for MP3 files"
repository = "https://github.com/GuillaumeGomez/mp3-metadata"
license = "MIT"

keywords = ["mp3", "metadata"]

[lib]
name = "mp3_metadata"
